server:
  port: 8080

spring:
  application:
    name: InternetBankingFicticio

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: jezz
    password: changeit
    initialization-mode: embedded # habilita inicializacao do script de carga apenas quando bd for em memoria

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC-3
    show-sql: true # logar as queries
    hibernate.ddl-auto: update # config do hibernate para atualizar os schemas
    defer-datasource-initialization: true # adia inicializacao datasource para carregar dados na base

  h2:
    console:
      enabled: true # habilitar console h2 pelo navegador
      path: /internetbanking-db-ui # url de acesso para o console h2 | default path: h2-console