package internetbankingficticio.service.transaction;

import internetbankingficticio.dto.transaction.TransactionCreateDto;
import internetbankingficticio.dto.transaction.TransactionDto;
import internetbankingficticio.enums.transaction.TransactionCommand;
import internetbankingficticio.exception.ResourceNotFoundException;
import internetbankingficticio.exception.TransactionAmmountValidationException;

public interface TransactionCreatorServiceIF {
    TransactionCommand getTransactionCreatorCommand();
    TransactionDto createTransaction(TransactionCreateDto transactionCreateDto) throws ResourceNotFoundException, TransactionAmmountValidationException;
}
